### ISSUE TITLE
Team Formation

### ISSUE THREAD

**Issue by wdoug** [codefordenver/encorelink#1]
### Form a team of 2 to 5 people

Gather with at least one other person to create a team around an idea or a problem that's interesting to you.

Spend a few minutes asking these questions:
- What's our shared vision?
  - Talk about what goal you want to accomplish as a team.
- What's in it for me?
  - Talk about each individual's motivation - what do you as an individual want to learn or accomplish?
- What talents do we bring to the table?
  - Share a bit of your experience and skills
- Set working agreements
  - What agreements do you, as a team, want to make for the time you are spending together?
  - Suggestions:
    - Show Up On Time
    - Agree on when you'll meet
    - "Art of the Possible" - no idea is stupid, let's consider everything.
    - Be Present - when you're here, you're here, be intentional with your time.

That's it! Now you have a clear goal for your team to accomplish and you know why each of you are here.

**Comment by slamflipstrom** [comment]
Emma, Brett, Julia, Daren, Fred, and Sam (myself) have all expressed interest in contributing to this project.

**Comment by slamflipstrom** [comment]
Sam and Fred will spearhead the development efforts for the time being. Emma, Brett, Darren, and Julia are handling the business logistics and solution planning.

**Comment by LaurieLinz** [comment]
I was unable to attend tonight but I am interested in contributing to the
development as well.

Laurie

**Comment by slamflipstrom** [comment]
Thanks @LaurieLinz! Whoever wants to jump in and contribute is more than welcome to join!
