### ISSUE TITLE
Password Recovery

### ISSUE THREAD

**Issue by darrenrichmond** [codefordenver/encorelink#100]
As any kind of user, I need to be able to recover or reset my password, in case I forget it. Link needs to be from the Login page.

![image](https://cloud.githubusercontent.com/assets/18622286/17916201/5a0b76be-696e-11e6-96cc-f328a3a3175f.png)

**Comment by wdoug** [comment]
How high of a priority is this?

**Comment by darrenrichmond** [comment]
I was prioritizing things by where they are in the flow, and this is at the beginning. Also, if you are going to have a login that requires a password, you have to have a way for me to recover if I forget. I'd be willing to hear arguments to bump the priority down.
