### ISSUE TITLE
Musician Creates/Edits Profile

### ISSUE THREAD

**Issue by darrenrichmond** [codefordenver/encorelink#102]
As a Musician, I need to create a Profile so that Organizers can decide whether to have me perform. I need to be able to edit this profile later if things change. 

![image](https://cloud.githubusercontent.com/assets/18622286/17956060/f80088c0-6a43-11e6-9982-968279e72e87.png)
![image](https://cloud.githubusercontent.com/assets/18622286/17956067/058013e4-6a44-11e6-895c-53fc868c2ea3.png)

**Comment by darrenrichmond** [comment]
Need to define required and optional fields.

**Comment by Shuzy** [comment]
Keeping these fields: (pending)
Phone Number, (remove Date of Birth), 
City, State, Zipcode, 
Profile Picture, (remove all education fields),
Instrument/voice (required field), 
Secondary Instrument/voice (optional field), (remove the music you're sharing), (remove the reason of sharing),
Video/Audio link, 
Profile (text paragraph), 
Yes, I'm over 21. (check box)
