### ISSUE TITLE
Contact from Event Details

### ISSUE THREAD

**Issue by darrenrichmond** [codefordenver/encorelink#104]
As an Organizer or Musician, I need to be able to chat with the Organizer who scheduled the event or the Musician signing up, so that we can clarify details of the performance. We need to figure out the best UI for this (maybe just email for now?). When the chat is sent, it should send an email, and should show up in their Chat list (#103).

![image](https://cloud.githubusercontent.com/assets/18622286/17917345/c3a8ad1c-6978-11e6-8e14-4efdd05a1980.png)

**Comment by darrenrichmond** [comment]
Putting back to backlog until Shannon is done with #100 - email capability

**Comment by KeynesYouDigIt** [comment]
models/event.json - line 33 references User that owns event, link should point to a DM or his email
