### ISSUE TITLE
Musician Dashboard: Styling

### ISSUE THREAD

**Issue by darrenrichmond** [codefordenver/encorelink#106]
-- Blocked by 230

- View performances I have signed up for, but have not yet been approved by the Organizer, with a link to Event Details
- View performances I have signed up for and have been approved by the Organizer, with a link to Event Details
- View performances I have signed up for and have been rejected by the Organizer, with a link to Event Details

After signing up for first event:
![image](https://cloud.githubusercontent.com/assets/18622286/17917677/e4265cb2-697b-11e6-9392-0656c6cce1fc.png)

![image](https://cloud.githubusercontent.com/assets/18622286/17917677/e4265cb2-697b-11e6-9392-0656c6cce1fc.png)

**Comment by wdoug** [comment]
This seems like a couple different issues. Should we split them out that way into different cards?

**Comment by darrenrichmond** [comment]
Will review needs once #230 - Musician Dashboard No Styling - is complete

**Comment by bericson** [comment]
Verified that the functionality is working as requested/specified, and added some styling to tighten things up a bit in the UI.
