### ISSUE TITLE
Improve Event Creation Form

### ISSUE THREAD

**Issue by wdoug** [codefordenver/encorelink#107]
![image](https://cloud.githubusercontent.com/assets/18622286/17955873/7a162682-6a42-11e6-9413-a5ad486d9cb4.png)

![image](https://cloud.githubusercontent.com/assets/18622286/17955875/8c171bd4-6a42-11e6-9f6d-46c3be13e873.png)

![image](https://cloud.githubusercontent.com/assets/18622286/17955884/99cb8f44-6a42-11e6-9455-c258ebdaf6b0.png)

**Comment by vijoditz-agustin** [comment]
This is being worked on #227
