### ISSUE TITLE
Task: Create Application Diagram

### ISSUE THREAD

**Issue by slamflipstrom** [codefordenver/encorelink#19]
![image](https://cloud.githubusercontent.com/assets/18622286/17915409/90bb3aca-6967-11e6-9d60-c9ae43671c17.png)

**Comment by slamflipstrom** [comment]
![img_20160620_204143](https://cloud.githubusercontent.com/assets/8062052/16216558/deec907a-3728-11e6-9d7e-f509a9c16ea9.jpg)

**Comment by darrenrichmond** [comment]
http://www.gliffy.com/go/publish/image/10979575/L.png

**Comment by darrenrichmond** [comment]
Updated process flow based on 8/22 project night https://www.gliffy.com/go/publish/image/11043599/L.png
