### ISSUE TITLE
create MVP through Google Calendar

### ISSUE THREAD

**Issue by Shuzy** [codefordenver/encorelink#21]

**Comment by darrenrichmond** [comment]
Here is a simple calendar with a couple of booked performance requests: https://calendar.google.com/calendar/embed?src=tte1m4pue2v512s5a0gggl26h8%40group.calendar.google.com&ctz=America/Denver

Here is a description of how to use the MVP to test our hypotheses: https://github.com/codefordenver/music-volunteers/blob/master/mvp1-google_calendar.md
