### ISSUE TITLE
organizer dashboard showing all events

### ISSUE THREAD

**Issue by nlkluth** [codefordenver/encorelink#283]
The organizer dashboard is showing all events instead of just the events belonging to an organizer

**Comment by darrenrichmond** [comment]
This looks fixed to me - can we move to done?

**Comment by nlkluth** [comment]
@wdoug is latest deployed to heroku?

**Comment by wdoug** [comment]
@nlkluth I just deployed latest to heroku to get some of the updates, and this bug is definitely present.

**Comment by wdoug** [comment]
I believe this can be closed now as of PR #288.
I am going to mark as closed. Feel free to reopen if that is not the case @nlkluth
