### ISSUE TITLE
Clarify signing up as an organizer vs musician

### ISSUE THREAD

**Issue by wdoug** [codefordenver/encorelink#287]
Right now it is really unclear what you are signing up as if you don't check the musician checkbox.

Probably the cheapest improvement for this would be to have a radio button for the two options instead of just the musician checkbox. We could definitely discuss other ideas though.

**Comment by with-a-k** [comment]
Oh, someone else thought of this! Radio options sound simpler and maybe clearer than what I had in mind, which flipped between the options.

**Comment by with-a-k** [comment]
There are two branches for this right now - 287_clarify_signup and 287_clarify_signup_2.
Things to investigate with regards to the latter:
 - can we still have the checkbox on the page and just CSS it out of visibility
 - move the styling from the first branch onto the second one
