### ISSUE TITLE
Prototype of GUI

### ISSUE THREAD

**Issue by lcrostarosa** [codefordenver/encorelink#31]

**Comment by darrenrichmond** [comment]
Notes on 7/21/16 user interview with Organizer https://docs.google.com/document/d/1evXISBW3hSLNJVOMJifRrx9ZgmTAGs5M6XMpOVWoMbY/edit#

**Comment by darrenrichmond** [comment]
https://xd.adobe.com/view/557d2997-a1b1-4f73-51ac-f90620c619bc/ was used in interview with Consuelo 7/21/2016 (first Organizer to provide feedback). This version was complete for Organizers. Next step is to complete for Musicians.

**Comment by darrenrichmond** [comment]
Wireframes as of 8/22/16 https://xd.adobe.com/view/557d2997-a1b1-4f73-51ac-f90620c619bc/

**Comment by wdoug** [comment]
Can we close this issue now?
