### ISSUE TITLE
Pitch Prototype to nursing homes

### ISSUE THREAD

**Issue by lcrostarosa** [codefordenver/encorelink#32]

**Comment by darrenrichmond** [comment]
1st prototype (https://xd.adobe.com/view/557d2997-a1b1-4f73-51ac-f90620c619bc/) pitched to Consuelo at Pearl St. health and rehab on 7/21/16. See https://docs.google.com/document/d/1evXISBW3hSLNJVOMJifRrx9ZgmTAGs5M6XMpOVWoMbY/edit for details and feedback.

**Comment by darrenrichmond** [comment]
Second prototype (https://xd.adobe.com/view/557d2997-a1b1-4f73-51ac-f90620c619bc/) pitched to Heather at Littleton Heath and Rehab and to Jessica at Julia Temple 7/29/16. See https://docs.google.com/document/d/1MmZ_ovBM2UhQACNsB2Y0taKTfUXNZZ3nuXG0rWMgTV8/edit for Heather and https://docs.google.com/document/d/1kJDxp9y9JeUnXhEmgSqBeLdhgZ_eDp9BFJtk8Db8akk/edit for Jessica.
