### ISSUE TITLE
Organizer View a Musician's Profile

### ISSUE THREAD

**Issue by darrenrichmond** [codefordenver/encorelink#36]
As an Organizer, I need to be able to see some of the details from the Volunteer's Profile, so that I can make sure that the person who booked will be appropriate for my event. I should only be able to see a Musician's Profile after that Volunteer has registered for an event, but once that happens, I should be able to view it anytime.

![image](https://cloud.githubusercontent.com/assets/18622286/17798115/cac3d82e-658b-11e6-8349-9697947e79e4.png)

![image](https://cloud.githubusercontent.com/assets/18622286/17798101/ac2fe83a-658b-11e6-932e-c3c83591c515.png)

**Comment by wdoug** [comment]
Few things Julia had written down for this page:

After you sign up for an account, please make sure you complete your profile for us to review the organization membership. After 1-2 days, you will receive an email from us to confirm your organization registration and then you will be able to schedule music performances!

Username:_____________
Password:______________
Confirm Password:_______

[Create account]

Please complete your profile: 
Organization Name:_____________________ 
Your name:_____________
Job title:________________
Address:________________
City:______________
State:____________ Zipcode:_____________
Email:__________________
Phone:______________ Ext:____________
Best Contact ways/time: ________________
Special notes (about the facility) 
(Text box)

Please read the disclaimer here. By signing up you agree to this agreement. 
[ ] Yes, I agree

[ Sign up ]
