### ISSUE TITLE
Links To Registration

### ISSUE THREAD

**Issue by Hamorim85** [codefordenver/encorelink#45]
As an Organizer or Volunteer, I need a way to get to the appropriate registration page so I can register as an active user. There should be a link from the login page, but should be reachable from anywhere. We do not need links to registration for administrators.

![image](https://cloud.githubusercontent.com/assets/18622286/17759852/493c4c88-64b8-11e6-9c8b-30568a9f14d8.png)

**Comment by darrenrichmond** [comment]
I'm ranking this top because we can use the email campaign with a simple landing page that says "Thanks for your interest! We'll contact you when we're ready!" - that will allow us to track how many organizers are interested enough in our product to initiate registration.

**Comment by Hamorim85** [comment]
Good point  Darren, One of our focus moving forward might be actually be emailing AD's so they can get on a list. Might actually be a good measure of what the adoption rate might be.

**Comment by darrenrichmond** [comment]
Closing as no longer needed, now that registration is on the Home page.
