### ISSUE TITLE
Research Potential Partners

### ISSUE THREAD

**Issue by wdoug** [codefordenver/encorelink#5]
### Research Potential Partners
- Teams should identify at least two potential project partners.
- Potential partners should be non-profit, government, or quasi-governmental organizations, community-based organizations or other community groups or organizations consistent with the CfD mission.
  Teams should identify if the initial idea is consistent with potential partner organization mission and goals.
- Teams should be able to clearly identify how potential partners could used the built solution, how they would maintain the end product and partners overall role in the built solution product live cycle.

**Comment by hasuf** [comment]
Potential Partners:
- Children's Hospital (Julia has a contact, has volunteered there before and had musicians perform there)
- Englewood Acute and Rehab Center (Julia has a contact)
- DU for getting students involved (Julia knows professors)

**Comment by Shuzy** [comment]
University of Denver, UC Boulder, UC Denver, Colorado Non- Profit Association, Colorado Attorneys for the Arts, Modus volunteers, Bessie's Hope, http://www.breadandroses.org/ (based in CA)

**Comment by darrenrichmond** [comment]
julia has a list of potential partners in google docs here: https://docs.google.com/spreadsheets/d/1LDgzKMHSpH1hUbpMw9CoAuTHDQZAugIYUwTOkjIqigI/edit#gid=0
