### ISSUE TITLE
Volunteer Registration

### ISSUE THREAD

**Issue by Shuzy** [codefordenver/encorelink#54]
As a Volunteer, I need to be able to register an account, so that I can log in and search for nearby Events. Text will change, but structure is good. Registration should take you back to Log In page. 

![image](https://cloud.githubusercontent.com/assets/18622286/17760294/0ca554a0-64bc-11e6-84a5-5ade62445cdd.png)

**Comment by darrenrichmond** [comment]
This is now part of Home Page #84, so closing.
