### ISSUE TITLE
Musician Get to Registration

### ISSUE THREAD

**Issue by Shuzy** [codefordenver/encorelink#55]

**Comment by darrenrichmond** [comment]
I'm ranking this super high because we can use the email campaign with a simple landing page that says "Thanks for your interest! We'll contact you when we're ready!" - that will allow us to track how many musicians are interested enough in our product to initiate registration.

**Comment by darrenrichmond** [comment]
Closing as duplicate of 45, now that this encompases both Organizer an Volunteer roles.
