### ISSUE TITLE
User Login: Skin

### ISSUE THREAD

**Issue by Shuzy** [codefordenver/encorelink#56]
As a user, I need to be able to log in to the application. Only registered users can login. Once my login is confirmed, I should be taken to the appropriate page for my role (Organizer, Volunteer, Admin, etc.)

![image](https://cloud.githubusercontent.com/assets/18622286/17759707/e00043e2-64b6-11e6-8cb5-d36d275403b3.png)

**Comment by wdoug** [comment]
Functionally this is already done (well outside of showing errors to the user, which I think we have a separate card for). @darrenrichmond do we want to repurpose this card for making it styled and pretty?
