### ISSUE TITLE
What Makes Your Solution Different?

### ISSUE THREAD

**Issue by wdoug** [codefordenver/encorelink#6]
### What is your Unique Value Proposition?

Fill in Box 3, the "Unique Value Proposition."

![leancanvas-box3](https://cloud.githubusercontent.com/assets/100216/12663596/cd50f72e-c5e6-11e5-8d40-4daeaf0365a3.png)
#### What is a UVP?

Your unique value proposition is the promise you're making to your customer that's compelling enough for them to jump on board.
#### Writing a UVP

Here are two suggested formats: 

1) Ask yourself: "If I solve _the problem_ `[by doing this]` for _my customer_, is that compelling?" 

When you can substitute `[by doing this]` with something compelling, that's the Unique Value Proposition you're proposing.

2) Complete the statement: "I can promise [the customer in Box 1] who faces [the problem in Box 2] that I can give them [unique value proposition in Box 3]."

Lastly, don't forget to fill out the `High Level Concept`! This serves as a clear way to describe who you are. For Uber, this would be "Order a taxi with your phone." It can also be an 'x for y' concept like "Instagram for Pet Lovers."

**Comment by Shuzy** [comment]
Simplify the scheduling process for musician volunteers and healthcare organizations.
Less scheduling, more music
Background checking volunteers
This solution should be expandable to many cities and universities compare to current solutions that are mostly local and stays local.
