### ISSUE TITLE
Musician Sign Up for Event

### ISSUE THREAD

**Issue by Shuzy** [codefordenver/encorelink#60]
As a Volunteer, I need to be able to register for (book) an event, so that the Organizer knows I want to perform. Once I register for an event, the following should happen:
- the event should show up as one of my registered events in the calendar
- the system should send a notification (email by default) to the Organizer that I have registered
- the event should show up in the Organizer's list of Registered events
- The Organizer should see me in the Chat page and be able to chat with me
- I should be taken to the Volunteer Calendar view, where I can see the Event as Registered by me

![image](https://cloud.githubusercontent.com/assets/18622286/17797962/6bf61308-658a-11e6-9282-a6aab36e800a.png)

**Comment by wdoug** [comment]
@fredmon3 how far did you get on this / @vijoditz-agustin did you start working on this?
