### ISSUE TITLE
Brainstorm solutions

### ISSUE THREAD

**Issue by wdoug** [codefordenver/encorelink#7]
### Brainstorm Solutions
- [ ] Using a [timer](https://www.google.com/#q=timer), take 5 minutes to write down as many rough ideas on sticky notes as you can.
- [ ] Go around as a team and put your sticky notes on a wall as you say what you wrote.
- [ ] Group similar ideas together.

When you're finished, you're ready to move on to creating paper prototypes!

![screen shot 2016-01-28 at 4 25 30 pm](https://cloud.githubusercontent.com/assets/100216/12662189/d40df98c-c5db-11e5-9517-e3d613a904b9.png)

**Comment by darrenrichmond** [comment]
I think we skipped this, but are a bit beyond it now. Do we want to revisit this on Mon 7/25? Or are we ready to work in story maps?

**Comment by darrenrichmond** [comment]
We did this as part of User Story Mapping. We now have a full process flow in #19, so calling this done.
