### ISSUE TITLE
Paper Prototypes

### ISSUE THREAD

**Issue by wdoug** [codefordenver/encorelink#8]
### Paper Prototypes

You should have several ideas from your brainstorming session. 
- [ ] Group any similar ideas together.
- [ ] Take one idea (or group of ideas) per person and spend [5 minutes](https://www.google.com/#q=timer) building a paper prototype.
#### How to build a paper prototype

It's simple! All you need is a piece of paper and something to write with to draw out your solution. 

No one expects it to be pretty, don't worry! Add as much detail as you can around how your solution might look or work.

![paperprototype](https://cloud.githubusercontent.com/assets/100216/12632529/f30acade-c515-11e5-9629-ddb0d8dcfa80.gif)

**Comment by slamflipstrom** [comment]
![img_20160516_2014442_rewind](https://cloud.githubusercontent.com/assets/8062052/16215432/70ac62e2-371f-11e6-93a1-c68846534777.jpg)
